name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.os }}-${{matrix.file}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest # x64
        - ubuntu-24.04-arm # arm64
        - macOS-13 # "Intel"
        - macOS-latest # arm64

        file:
        - fetchFromGitHub.nix
        - fetchgit.nix
        - nix-prefetch-git.nix
        - nix-prefetch-github.nix

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build
      run : |
        nix-build --show-trace ".github/exprs/${{matrix.file}}"
